=== symfony/symfony/src/Symfony/Component/Serializer/Mapping/Loader/schema/dic/serializer-mapping/serializer-mapping-1.0.xsd
<?xml version="1.0" ?>

<xsd:schema xmlns="http://symfony.com/schema/dic/serializer-mapping"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://symfony.com/schema/dic/serializer-mapping"
            elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation><![CDATA[
      Symfony Serializer Mapping Schema, version 1.0
      Authors: Kévin Dunglas, Samuel Roze

      A serializer mapping connects attributes with serialization groups.
    ]]></xsd:documentation>
    </xsd:annotation>

    <xsd:element name="serializer" type="serializer" />

    <xsd:complexType name="serializer">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        The root element of the serializer mapping definition.
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="class" type="class" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="class">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Contains serialization groups for a single class.

        Nested elements may be class property and/or getter definitions.
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="attribute" type="attribute" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="discriminator-map" type="discriminator-map" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="discriminator-map">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="mapping" type="discriminator-map-mapping" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="type-property" type="xsd:string" use="required" />
        <xsd:attribute name="default-type" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="discriminator-map-mapping">
        <xsd:attribute name="type" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="attribute">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Contains serialization groups and max depth for attributes. The name of the attribute should be given in the "name" option.
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="group" type="xsd:string" maxOccurs="unbounded" />
            <xsd:element name="serialized" type="serialized" maxOccurs="unbounded" />
            <xsd:element name="context" type="context" maxOccurs="unbounded" />
            <xsd:element name="normalization_context" type="context" maxOccurs="unbounded" />
            <xsd:element name="denormalization_context" type="context" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="max-depth">
            <xsd:simpleType>
                <xsd:restriction base="xsd:integer">
                    <xsd:minInclusive value="0" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="serialized-name" type="serialized-name-or-path" />
        <xsd:attribute name="serialized-path" type="serialized-name-or-path" />
        <xsd:attribute name="ignore" type="xsd:boolean" />
    </xsd:complexType>

    <xsd:complexType name="serialized">
        <xsd:sequence minOccurs="0">
            <xsd:element name="group" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="name" type="serialized-name-or-path" />
        <xsd:attribute name="path" type="serialized-name-or-path" />
    </xsd:complexType>

    <xsd:complexType name="context">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="group" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="entry" type="context-root-entry" maxOccurs="unbounded" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="context-root-entry" mixed="true">
        <xsd:sequence minOccurs="0">
            <xsd:element name="entry" type="context-entry" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" use="required" />
    </xsd:complexType>

    <xsd:complexType name="context-entry" mixed="true">
        <xsd:sequence minOccurs="0">
            <xsd:element name="entry" type="context-entry" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" />
    </xsd:complexType>

    <xsd:simpleType name="serialized-name-or-path">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== symfony/symfony/src/Symfony/Component/Serializer/Tests/Fixtures/serialization.xml
<?xml version="1.0" ?>

<serializer xmlns="http://symfony.com/schema/dic/serializer-mapping"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://symfony.com/schema/dic/serializer-mapping https://symfony.com/schema/dic/serializer-mapping/serializer-mapping-1.0.xsd">

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\GroupDummy">
        <attribute name="foo">
            <group>group1</group>
            <group>group2</group>
        </attribute>

        <attribute name="bar">
            <group>group2</group>
        </attribute>
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\MaxDepthDummy">
        <attribute name="foo" max-depth="2" />
        <attribute name="bar" max-depth="3" />
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\SerializedNameDummy">
        <attribute name="foo" serialized-name="baz" />
        <attribute name="bar" serialized-name="qux" />
        <attribute name="duux">
            <serialized name="duxi" />
            <serialized name="duxa">
                <group>a</group>
            </serialized>
        </attribute>
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\SerializedPathDummy">
        <attribute name="three" serialized-path="[one][two]" />
        <attribute name="seven" serialized-path="[three][four]" />
        <attribute name="eleven">
            <serialized path="[five][six]" />
            <serialized path="[six][five]">
                <group>a</group>
            </serialized>
        </attribute>
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\SerializedPathInConstructorDummy">
        <attribute name="three" serialized-path="[one][two]" />
        <attribute name="eleven" serialized-path="[five][six]">
            <serialized path="[six][five]">
                <group>a</group>
            </serialized>
        </attribute>
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\AbstractDummy">
        <discriminator-map type-property="type" default-type="second">
            <mapping type="first" class="Symfony\Component\Serializer\Tests\Fixtures\Attributes\AbstractDummyFirstChild" />
            <mapping type="second" class="Symfony\Component\Serializer\Tests\Fixtures\Attributes\AbstractDummySecondChild" />
        </discriminator-map>

        <attribute name="foo" />
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\IgnoreDummy">
        <attribute name="ignored1" ignore="true" />
        <attribute name="ignored2" ignore="true" />
        <attribute name="notIgnored" ignore="false" />
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\ContextDummyParent">
        <attribute name="parentProperty">
            <normalization_context>
                <entry name="prop">dummy_parent_value</entry>
            </normalization_context>
        </attribute>
        <attribute name="overriddenParentProperty">
            <normalization_context>
                <entry name="prop">dummy_parent_value</entry>
            </normalization_context>
        </attribute>
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\ContextDummy">
        <attribute name="foo">
            <context>
                <entry name="foo">value</entry>
                <entry name="bar">value</entry>
                <entry name="nested">
                    <entry name="nested_key">nested_value</entry>
                </entry>
                <entry name="array">
                    <entry>first</entry>
                    <entry>second</entry>
                </entry>
            </context>
            <context>
                <group>a</group>
                <entry name="bar">value_for_group_a</entry>
            </context>
        </attribute>
        <attribute name="bar">
            <normalization_context>
                <group>a</group>
                <group>b</group>
                <entry name="format">d/m/Y</entry>
            </normalization_context>
            <denormalization_context>
                <group>a</group>
                <group>b</group>
                <entry name="format">m-d-Y H:i</entry>
            </denormalization_context>
        </attribute>
        <attribute name="overriddenParentProperty">
            <normalization_context>
                <entry name="prop">dummy_value</entry>
            </normalization_context>
        </attribute>
        <attribute name="methodWithContext">
            <context>
                <entry name="method">method_with_context</entry>
            </context>
        </attribute>
    </class>

    <class name="Symfony\Component\Serializer\Tests\Fixtures\Attributes\MaxDepthZeroDummy">
        <attribute name="child" max-depth="0" />
    </class>
</serializer>
